### ISSUE TITLE
XGB train call failed with exception: You can't mix new and old callback styles

### ISSUE THREAD

**Issue by charlesreid1acom** [aws/sagemaker-xgboost-container#303]
Hello,

A month ago we had a minimum viable prototype for a SageMaker pipeline. Last Thursday our MVP was working fine. But this week the training step broke, meaning the rest of the pipeline is also broken. When we run the same code that was working fine last week, it fails this week with the following:

```
XGB train call failed with exception: You can't mix new and old callback styles.
```

This happens from within the training container. Here is the full output from the Estimator object's fit() call:

```
2022-08-27 00:36:36 Starting - Preparing the instances for trainingProfilerReport-1661560572: InProgress
......
2022-08-27 00:37:42 Downloading - Downloading input data
2022-08-27 00:37:42 Training - Downloading the training image......
2022-08-27 00:38:42 Training - Training image download completed. Training in progress...[2022-08-27 00:38:45.858 ip-10-0-65-114.ec2.internal:1 INFO utils.py:27] RULE_JOB_STOP_SIGNAL_FILENAME: None
[2022-08-27:00:38:45:INFO] Imported framework sagemaker_xgboost_container.training
[2022-08-27:00:38:45:INFO] Failed to parse hyperparameter objective value reg:squarederror to Json.
Returning the value itself
[2022-08-27:00:38:45:INFO] No GPUs detected (normal if no gpus installed)
[2022-08-27:00:38:45:INFO] Running XGBoost Sagemaker in algorithm mode
[2022-08-27:00:38:45:INFO] Determined delimiter of CSV input is ','
[2022-08-27:00:38:45:INFO] Determined delimiter of CSV input is ','
[2022-08-27:00:38:45:INFO] files path: /opt/ml/input/data/train
[2022-08-27:00:38:45:INFO] Determined delimiter of CSV input is ','
[2022-08-27:00:38:46:INFO] files path: /opt/ml/input/data/validation
[2022-08-27:00:38:46:INFO] Determined delimiter of CSV input is ','
[2022-08-27:00:38:46:INFO] Single node training.
[2022-08-27:00:38:46:INFO] Train matrix has 31829 rows and 125 columns
[2022-08-27:00:38:46:INFO] Validation matrix has 7959 rows
[2022-08-27 00:38:46.121 ip-10-0-65-114.ec2.internal:1 INFO json_config.py:91] Creating hook from json_config at /opt/ml/input/config/debughookconfig.json.
[2022-08-27 00:38:46.121 ip-10-0-65-114.ec2.internal:1 INFO hook.py:200] tensorboard_dir has not been set for the hook. SMDebug will not be exporting tensorboard summaries.
[2022-08-27 00:38:46.121 ip-10-0-65-114.ec2.internal:1 INFO profiler_config_parser.py:102] User has disabled profiler.
[2022-08-27 00:38:46.122 ip-10-0-65-114.ec2.internal:1 INFO hook.py:255] Saving to /opt/ml/output/tensors
[2022-08-27 00:38:46.122 ip-10-0-65-114.ec2.internal:1 INFO state_store.py:77] The checkpoint config file /opt/ml/input/config/checkpointconfig.json does not exist.
[2022-08-27:00:38:46:INFO] Debug hook created from config
[2022-08-27:00:38:46:ERROR] Reporting training FAILURE
[2022-08-27:00:38:46:ERROR] framework error: 
Traceback (most recent call last):
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_xgboost_container/algorithm_mode/train.py", line 238, in train_job
    bst = xgb.train(train_cfg, train_dmatrix, num_boost_round=num_round-iteration, evals=watchlist,
  File "/miniconda3/lib/python3.8/site-packages/xgboost/training.py", line 188, in train
    bst = _train_internal(params, dtrain,
  File "/miniconda3/lib/python3.8/site-packages/xgboost/training.py", line 61, in _train_internal
    assert all(isinstance(c, callback.TrainingCallback)
AssertionError: You can't mix new and old callback styles.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_containers/_trainer.py", line 84, in train
    entrypoint()
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_xgboost_container/training.py", line 93, in main
    train(framework.training_env())
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_xgboost_container/training.py", line 89, in train
    run_algorithm_mode()
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_xgboost_container/training.py", line 63, in run_algorithm_mode
    sagemaker_train(
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_xgboost_container/algorithm_mode/train.py", line 178, in sagemaker_train
    train_job(**train_args)
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_xgboost_container/algorithm_mode/train.py", line 304, in train_job
    raise exc.AlgorithmError("{}:\n {}".format(exception_prefix, str(e)))
sagemaker_algorithm_toolkit.exceptions.AlgorithmError: XGB train call failed with exception:
 You can't mix new and old callback styles.
XGB train call failed with exception:
 You can't mix new and old callback styles.

2022-08-27 00:38:59 Uploading - Uploading generated training model
2022-08-27 00:38:59 Failed - Training job failed

---------------------------------------------------------------------------
UnexpectedStatusException                 Traceback (most recent call last)
<ipython-input-35-fe7be97cffc7> in <module>
----> 1 estimator.fit(inputs=data_inputs)

/opt/conda/lib/python3.7/site-packages/sagemaker/workflow/pipeline_context.py in wrapper(*args, **kwargs)
    246             return self_instance.sagemaker_session.context
    247 
--> 248         return run_func(*args, **kwargs)
    249 
    250     return wrapper

/opt/conda/lib/python3.7/site-packages/sagemaker/estimator.py in fit(self, inputs, wait, logs, job_name, experiment_config)
   1062         self.jobs.append(self.latest_training_job)
   1063         if wait:
-> 1064             self.latest_training_job.wait(logs=logs)
   1065 
   1066     def _compilation_job_name(self):

/opt/conda/lib/python3.7/site-packages/sagemaker/estimator.py in wait(self, logs)
   2145         # If logs are requested, call logs_for_jobs.
   2146         if logs != "None":
-> 2147             self.sagemaker_session.logs_for_job(self.job_name, wait=True, log_type=logs)
   2148         else:
   2149             self.sagemaker_session.wait_for_job(self.job_name)

/opt/conda/lib/python3.7/site-packages/sagemaker/session.py in logs_for_job(self, job_name, wait, poll, log_type)
   3851 
   3852         if wait:
-> 3853             self._check_job_status(job_name, description, "TrainingJobStatus")
   3854             if dot:
   3855                 print()

/opt/conda/lib/python3.7/site-packages/sagemaker/session.py in _check_job_status(self, job, desc, status_key_name)
   3392                 message=message,
   3393                 allowed_statuses=["Completed", "Stopped"],
-> 3394                 actual_status=status,
   3395             )
   3396 

UnexpectedStatusException: Error for Training job sagemaker-xgboost-2022-08-27-00-36-12-698: Failed. Reason: AlgorithmError: framework error: 
Traceback (most recent call last):
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_xgboost_container/algorithm_mode/train.py", line 238, in train_job
    bst = xgb.train(train_cfg, train_dmatrix, num_boost_round=num_round-iteration, evals=watchlist,
  File "/miniconda3/lib/python3.8/site-packages/xgboost/training.py", line 188, in train
    bst = _train_internal(params, dtrain,
  File "/miniconda3/lib/python3.8/site-packages/xgboost/training.py", line 61, in _train_internal
    assert all(isinstance(c, callback.TrainingCallback)
AssertionError: You can't mix new and old callback styles.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_containers/_trainer.py", line 84, in train
    entrypoint()
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_xgboost_container/training.py", line 93, in main
    train(framework.training_env())
  File "/miniconda3/
```

We had a kernel from last week's session (a kernel that successfully ran the pipeline) that was not cleaned up, so I was able to check the output of pip freeze from last week and compare it to the output of pip freeze from the notebook container that failed. They were exactly the same. They are also pointing at data sets that we confirmed did not change since last week. The only thing that we think could be different between then and now is the XGBoost container image.

I also launched the pipeline from a Base Python 3 image (3.6), and from a Data Science image (3.7), and even the Data Science 2.0 image, with no change in the way the pipeline failed.

It also seems that someone else reported this issue for a SageMaker example notebook yesterday: https://github.com/aws/amazon-sagemaker-examples/issues/3578

(I should also mention, downgrading to previous versions of XGBoost is not possible, as we have issues with the input data format with older versions.)

**Comment by mabunday** [comment]
We've isolated this down to XGB versions from 3.0.0 onwards. See: https://github.com/aws/sagemaker-xgboost-container/pull/301

The above PR should fix the issue but it'll be another week or so before the change is fully deployed to all regions.

Do you remember if a different image was previously used? This shouldn't affect 1.2, but it would affect our 1.3 and 1.5 images.

**Comment by charlesreid1acom** [comment]
We are using us-east-1. We have been using the 1.5-1 image the entire time. We get our container image URI like so:

```
xgboost_container = sagemaker.image_uris.retrieve("xgboost", "us-east-1", "1.5-1")
```

**Comment by mabunday** [comment]
Thanks for the information.

That's interesting if you've been using the 1.5-1 image the entire time and it was previously working. Here you can see the change in XGB-1.3.0 that's causing the failure: https://github.com/dmlc/xgboost/blob/v1.3.0/python-package/xgboost/training.py#L92-L93

I'll double check that there isn't something else that suddenly caused this to be an issue, but in any case once the new image is deployed it should resolve the error so I'll let you know once it's in us-east-1.

**Comment by charlesreid1acom** [comment]
I checked, the last successful training job was August 18, 2022, 22:50 UTC

Training image was 683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-xgboost:1.5-1

The next training job failed and was at August 26, 2022 21:04 UTC

Training image was same, 683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-xgboost:1.5-1

**Comment by mabunday** [comment]
I just checked and the last deployment to us-east-1 for the 1.5-1 image was on July 18, 2022. Since then there haven't been any changes to the image, so it's odd that one of your training jobs succeeded while the other failed because they should have both been using the exact same image.

Can I trouble you to provide me the full job ARNs for both the successful and the failed job? I'd like to look into this a little bit more.

If the failed job had SageMaker Debugger attached to it and the successful one did not then that should explain the discrepancy.

**Comment by charlesreid1acom** [comment]
Sure, here is the successful 8/18 job arn: `arn:aws:sagemaker:us-east-1:021318967387:training-job/sagemaker-xgboost-2022-08-18-22-50-04-272`

and the unsuccessful 8/26 job arn: `arn:aws:sagemaker:us-east-1:021318967387:training-job/sagemaker-xgboost-2022-08-26-21-04-32-837`

**Comment by mabunday** [comment]
Hi, this change is being deployed and will be available in us-east-1 next Wednesday, September 7th. I'll write again on that day to confirm. Thanks for your patience.

**Comment by ilubis-pub** [comment]
Hi, we face the same problem as well with 1.5-1 in eu-central-1 region. Will the fix also be deployed there soon? thanks a lot for your help.

**Comment by haixiw** [comment]
Yes the fix will be deployed to eu-central-1 soon. I will notify here once the deployment finished

**Comment by mabunday** [comment]
@ilubis-pub Hi, this change is available in eu-central-1 now. Thank you for your patience!

**Comment by Matts966** [comment]
@mabunday 
Hi, we face this `You can't mix new and old callback styles.` issue with 1.5-1 in ap-northeast-1 region.
Will the fix also be deployed there soon?
Thank you 🙏

**Comment by mabunday** [comment]
@Matts966 Yes, it will be deployed world-wide by the end of the week. Thank you!

**Comment by mabunday** [comment]
Change has been deployed world-wide.
