### ISSUE TITLE
'XGBRegressor' object has no attribute 'set_param' | AttributeError: 'XGBRegressor' object has no attribute 'set_param'

### ISSUE THREAD

**Issue by rubencg195** [aws/sagemaker-xgboost-container#389]
I am having the following issue when using tag 1.5-1 which has xgboost==1.5.2 installed based on the dockerfile. The model I'm trying to load was trained using version 1.5.0. 

```
Traceback (most recent call last):
  File "/miniconda3/lib/python3.8/site-packages/gunicorn/arbiter.py", line 586, in spawn_worker
    worker.init_process()
  File "/miniconda3/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 203, in init_process
    super(GeventWorker, self).init_process()
  File "/miniconda3/lib/python3.8/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/miniconda3/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/miniconda3/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/miniconda3/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/miniconda3/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/miniconda3/lib/python3.8/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_xgboost_container/serving.py", line 29, in <module>
    from sagemaker_xgboost_container.algorithm_mode import serve
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_xgboost_container/algorithm_mode/__init__.py", line 23, in <module>
    serve.load_model()
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_xgboost_container/algorithm_mode/serve.py", line 135, in load_model
    return ScoringService.load_model(ensemble=serve_utils.is_ensemble_enabled())
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_xgboost_container/algorithm_mode/serve.py", line 71, in load_model
    cls.booster, cls.format = serve_utils.get_loaded_booster(ScoringService.MODEL_PATH, ensemble)
  File "/miniconda3/lib/python3.8/site-packages/sagemaker_xgboost_container/algorithm_mode/serve_utils.py", line 188, in get_loaded_booster
    booster.set_param("nthread", 1)
```

```
CopyAttributeError: 'XGBRegressor' object has no attribute 'set_param' | AttributeError: 'XGBRegressor' object has no attribute 'set_param'
```

Weirdly, when I try to install 1.5.2 and load it on a notebook, it works fine.

<img width="723" alt="image" src="https://user-images.githubusercontent.com/25628940/235036551-c5126455-addd-49f2-a260-01a14420b058.png">

**Comment by mabunday** [comment]
Check out https://stackoverflow.com/questions/74069566/sagemakerendpoint-attributeerror-xgbclassifier-object-has-no-attribute-set

The model file may have been serialized with pickle, which generally does not guarantee forward compatibility. If you load the model file and then reserialize it using the booster save it should work: https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html
