### ISSUE TITLE
XGBoost 0.90's `aucpr` evaluation metric is not supported by Sagemaker XGBoost image 0.90

### ISSUE THREAD

**Issue by mr2dark** [aws/sagemaker-xgboost-container#99]
XGBoost 0.90 supports `aucpr` as a valid value for the `eval_metric` learning task parameter. Please see: https://github.com/dmlc/xgboost/blob/release_0.90/doc/parameter.rst#learning-task-parameters

However, when we try to use it for Sagemaker's XGBoost image (versions `0.90-1` and `0.90-2`) training fails with the following message: `Hyperparameter eval_metric: value ['aucpr'] not in range ['rmse', 'mae', 'logloss', 'error', 'merror', 'mlogloss', 'auc', 'ndcg', 'map', 'poisson-nloglik', 'gamma-nloglik', 'gamma-deviance', 'tweedie-nloglik', 'accuracy', 'f1', 'mse']`

More complete error log:
```
ERROR:sagemaker-containers:Reporting training FAILURE
ERROR:sagemaker-containers:framework error:
Traceback (most recent call last):
  File "/miniconda3/lib/python3.6/site-packages/sagemaker_containers/_trainer.py", line 81, in train
    entrypoint()
  File "/miniconda3/lib/python3.6/site-packages/sagemaker_xgboost_container/training.py", line 94, in main
    train(framework.training_env())
  File "/miniconda3/lib/python3.6/site-packages/sagemaker_xgboost_container/training.py", line 90, in train
    run_algorithm_mode()
  File "/miniconda3/lib/python3.6/site-packages/sagemaker_xgboost_container/training.py", line 68, in run_algorithm_mode
    checkpoint_config=checkpoint_config
  File "/miniconda3/lib/python3.6/site-packages/sagemaker_xgboost_container/algorithm_mode/train.py", line 88, in sagemaker_train
    validated_train_config = hyperparameters.validate(train_config)
  File "/miniconda3/lib/python3.6/site-packages/sagemaker_algorithm_toolkit/hyperparameter_validation.py", line 225, in validate
    self.hyperparameters[hp].validate_range(value)
  File "/miniconda3/lib/python3.6/site-packages/sagemaker_algorithm_toolkit/hyperparameter_validation.py", line 176, in validate_range
    raise exc.UserError("Hyperparameter 
{}
: value 
{}
 not in range 
{}
".format(self.name, value, self.range))
sagemaker_algorithm_toolkit.exceptions.UserError: Hyperparameter eval_metric: value ['aucpr'] not in range ['rmse', 'mae', 'logloss', 'error', 'merror', 'mlogloss', 'auc', 'ndcg', 'map', 'poisson-nloglik', 'gamma-nloglik', 'gamma-deviance', 'tweedie-nloglik', 'accuracy', 'f1', 'mse']
Hyperparameter eval_metric: value ['aucpr'] not in range ['rmse', 'mae', 'logloss', 'error', 'merror', 'mlogloss', 'auc', 'ndcg', 'map', 'poisson-nloglik', 'gamma-nloglik', 'gamma-deviance', 'tweedie-nloglik', 'accuracy', 'f1', 'mse']```

**Comment by rizwangilani** [comment]
Hi,
I tested this with XGBoost 0.90-1 in us-west-2 and was unable to reproduce it. In what AWS region are you seeing this issue?

**Comment by mr2dark** [comment]
@rizwangilani Hi,
Yesterday I experienced this issue in the `eu-west-1` region with the `141502667606.dkr.ecr.eu-west-1.amazonaws.com/sagemaker-xgboost:0.90-2-cpu-py3` image.

**Comment by rizwangilani** [comment]
Hi @mr2dark ,

Understood. `aucpr` is indeed missing from `0.90-2` at the moment. It will be updated next week. 

However, you also mentioned that `aucpr` was also causing the same error for you in `0.90-1` - is that still the case? If yes, what region for `0.90-1`?

**Comment by rizwangilani** [comment]
I have rechecked: `0.90-1` in `eu-west-1` should support `aucpr`. Please let me know if you are still having any issues.

**Comment by mr2dark** [comment]
Hi @rizwangilani ,
I've also checked and can confirm that `0.90-1` in `eu-west-1` supports `aucpr`.
I had done the previous attempt with `0.90-1` a couple of months ago and then only with `0.90-2` this week, so I assumed the issue is still there.
Thank you for your assistance!
We can use `0.90-1` as of now but I'd rather leave this issue open until `aucpr` will work with `0.90-2`.
